### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by iamkristof** [meister03/discord-hybrid-sharding#68] opened 2022-09-27 17:17 UTC
Discord JS v13,
![image](https://user-images.githubusercontent.com/58638135/192592947-28d3fabd-0e61-43df-b661-1045a610f30b.png)
![image](https://user-images.githubusercontent.com/58638135/192592967-6b8615d7-6125-46f0-bc2f-58791fb32277.png)

I did everything correct i changed package json index to the shard file with the stuff and put my index file in there i added the stuff in the new client and get this error

**Comment by meister03** [comment] 2022-09-28 08:29
which file did you started?

**Comment by KieronWiltshire** [comment] 2022-10-30 22:57
I'm also getting this issue.

**Comment by Only-Moon** [comment] 2022-11-08 07:07
Yeah same issue, Im on discord.js v14 though

**Comment by anish2dev** [comment] 2022-11-10 15:09
> Discord JS v13, ![image](https://user-images.githubusercontent.com/58638135/192592947-28d3fabd-0e61-43df-b661-1045a610f30b.png) ![image](https://user-images.githubusercontent.com/58638135/192592967-6b8615d7-6125-46f0-bc2f-58791fb32277.png)
>
 The issue is due to your start command you are starting your bot file but you have to start your 
`shard/Cluster.js` file 

***The following methods can help you***
1. Make a folder name:
```
shard
```
2. Make a file name in that folder: 
```
Cluster.js 
```
3. Insert the following code in it 
```js
// Typescript: import { ClusterManager } from 'discord-hybrid-sharding'
const { ClusterManager } = require('discord-hybrid-sharding');

const manager = new Cluster.Manager(`${__dirname}/bot.js`, {
    totalShards: 7, // or 'auto'
    /// Check below for more options
    shardsPerClusters: 2,
    // totalClusters: 7,
    mode: 'process', // you can also choose "worker"
    token: 'YOUR_TOKEN',
});

manager.on('clusterCreate', cluster => console.log(`Launched Cluster ${cluster.id}`));
manager.spawn({ timeout: -1 });
```
4. Change the file path to your actual bot file 
5. Change your Start command to 
``` node shard/Cluster.js ```

**Comment by anish2dev** [comment] 2022-11-10 15:10
@meister03 you can close this

**Closed as completed** 2022-11-13 14:14 UTC
